---
title: "After Concord Hymn"
author: "N Wilson"
date: "2026-01-31"
output: html_document
---

Concord Hymn

By the rude bridge that arched the flood,\
Their flag to April's breeze unfurled,\
Here once the embattled farmers stood,\
and fired the shot heard round the world.\

The foe long since in silence slept;\
Alike the conqueror silent sleeps;\
And Time the ruined bridge has swept\
Down the dark stream which seaward creeps.\

On this green bank, by this soft stream,\
We set today a votive stone;\
That memory may their deed redeem,\
when like our sires, our sons are gone.\

Spirit, that made those heroes dare\
To die, and leave their children free,\
Bid Time and Nature gently spare\
The shaft we raise to them and thee.\

Ralph Waldo Emerson


I chose this poem to memorize in middle school, and though I have tried to memorize it again recently, the exact words and their order refuses to stick in my memory.
One of the things I have been looking for is an example of the sort of patriotism that I recognize in myself.
Maybe I should say something about being eligible to be a SAR?
I think of my self as a patriot in the sense that I take many of the ideals of The Revolution to be noble goals, and our task as patriots is to bring those ideals—liberty, equality, self-governance, and so forth— into being for more and more people. 
A greatness in the promise and process that we work towards, rather than something that has ever been instantiated. 
Concord Hymn was written by Emerson in memory of the battle of Lexington and Concord on the sixtieth anniversary of the event, to be read at the dedication of a monument to the same. 
I have been reading the poem almost daily for the past year and in the process thinking about what it says.

As a poem dedicated to people who died in battle it seems important he doesn't mention bravery or sacrifice.
The embattled farmers *dared* to revolt against the Crown,
standing with their flag in the breeze, firing the shot heard round the world.
This is heroism of a different sort than sacrifice.
To that action this votive stone is set, 'that memory may their deed redeem', 
how do we make sense of that sentiment?
In the act of remembrance symbolized and recalled by the monument stone,
we—those in attendance, and whomever looks upon the it in the future—will
regain possession of their deed; 
the commitment to the cause, *the daring to die*.
to die for freedom for one's children.
This is a lovely sentiment to offer for the founders of a nation.
On its own, if that was all there was, it wouldn't be so interesting. 
The second half of that line *to leave their children free* speaks of a process,
the fruits of which the actors, the embattled farmers, will never see. 
The daring is in planting a crop (these are farmers) you will never eat.
[Their shot heard round the world, was successfully reanimated to describe a notable bit of World Series baseball. 
I love baseball, but that re purposing is a testament to the anodyne aspect of battle—it happens all the time.]

In our time of political god-bothering, note the Spirit which motivates the daring is not named.
There is no Jesus or Christian God in the poem but an unnamed eminence,
one that was present at the time and is still present at the time of this dedication 
and will be present in the future. 
It is this Spirit which does the acting, it *made these heroes dare*,
and it is to this spirit which the poem is dedicated.
Is this the patriotism I have been looking for? 

What I enjoy most about the poem is the action of nature and time.
Unlike the spirit, nature is passive. 
The poem begins with natural imagery, we see the flood and the breeze before we see the farmers.
Sleep comes to the combatants,
time happens in the passive voice,
and there is an acknowledgement that time will continue *when like our sires our sons are gone*.
Nature's action in time is peaceful, it sweeps and creeps, green and soft.
Emerson implores Nature and time to *gently spare* this human work, 
the laying of the votive stone, 
as the rude bridge was not (ruined and swept away).

I like the imagery and internal rhyme in the line just past the half way point
*On this green bank, by this soft stream*.
This is the image I want to take from the poem, it invokes peace and comfort, contrast to the flood and violence of the poem's first half. 
It is the context in which the monument to that earlier time of struggle is lain.
What is being asked of the Spirit; to spare the memory of the heroic farmers and the votive stone from being figuratively swept out to sea. 

I want to believe that the experience of peace is the redemption of the memories of the patriots of the revolution. 
It is the Spirit which moves men to action that Emerson is trying to placate here.
He may be saying that the celebration of this monument, all the actors it celebrates 
(yes the revolutionary farmers, but also Spirit, Nature, and Time)
must be remembered for the redemption of that past as a landscape of peace.
Lose the memory (in all the parts explained), lose the peace.

This is not exactly the image of patriotism I was looking for, it's Emerson's version.
Reading the poem closely I get a better sense of his transcendentalism
(through a consideration of the Spirit and the passage of time).
There is a backwards looking aspect to memory, obviously, but the poem constantly connects actions in the past to the present and the future,
to die and leave their children free,
when like our sires our sons are gone.
This.